import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import Link from "next/link";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable}`}>
        <h1>
          Common content
        </h1>
        <nav>
          <ul>
            <Link href="/about"> 
              <li>
                about
              </li>
            </Link>

            <Link href="/content">
              <li>
                contact
              </li>
            </Link>
            <li>
              link 3
            </li>
          </ul>

        </nav>

        {children}
      </body>
    </html>
  );
}
